version: "3.8"
services:

  api:
    build:
      context: backend
      dockerfile: Dockerfile

    container_name: yar8-app-api
    ports:
      - "8000:8000"
    env_file:
      - backend/.env.local
    secrets:
      - gcp_service_account
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/gcp-service-account.json
    volumes:
      - ./backend:/app/
      - ./backend/secrets/gcp-service-account.json:/run/secrets/gcp-service-account.json:ro

  web:
    build: 
      context: frontend
      dockerfile: docker/local.Dockerfile
    container_name: yar8-app-ui
    ports:
      - "3000:80"
    

secrets:
  gcp_service_account:
    external: true